name: Test CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build and deploy with Maven
        run: echo $MAVEN_USERNAME
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
