name: Test CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Copy settings.xml
        run: cp $GITHUB_WORKSPACE/../.github/maven/settings.xml $HOME
      - name: View file
        run: cat $HOME/settings.xml

